# Generated by Django 4.2.13 on 2024-09-06 09:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('meeting_date', models.DateTimeField()),
                ('meeting_URL', models.URLField()),
                ('creation_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='messageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=30)),
                ('Log', models.CharField(max_length=1000)),
                ('creation_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentsMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US')),
                ('country_code', models.CharField(max_length=10)),
                ('creation_Date', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('email', 'phone_number', 'creation_Date')},
            },
        ),
    ]
