# Generated by Django 4.2.13 on 2024-09-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapyform', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parentsmeeting',
            unique_together=set(),
        ),
    ]
