# Generated by Django 4.2.13 on 2024-08-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapyform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('meeting_date', models.DateTimeField()),
                ('meeting_URL', models.URLField()),
                ('creation_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='messageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=30)),
                ('Log', models.CharField(max_length=1000)),
                ('creation_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='parentsmeeting',
            unique_together={('email', 'phone_number', 'creation_Date')},
        ),
    ]
