# Generated by Django 4.2.13 on 2024-09-08 17:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('therapyform', '0002_alter_parentsmeeting_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsmeeting',
            name='country_code',
            field=models.CharField(default='JO', max_length=10),
        ),
        migrations.AlterField(
            model_name='parentsmeeting',
            name='email',
            field=models.EmailField(default='default@default.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='parentsmeeting',
            name='full_name',
            field=models.CharField(default='From File', max_length=100),
        ),
        migrations.AlterField(
            model_name='parentsmeeting',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='JO'),
        ),
    ]
