# Generated by Django 4.2.13 on 2024-09-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapyform', '0003_alter_parentsmeeting_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='Error_Code',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='Error_Message',
            field=models.CharField(blank=True, default='Success', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='SID',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagelog',
            name='Status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
